name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: List generated APK
      run: find app/build/outputs -name "*.apk" | sort

    - name: Display APK information
      run: ls -la app/build/outputs/apk/debug/

    - name: Create release APK for download
      run: |
        mkdir -p release
        cp app/build/outputs/apk/debug/app-debug.apk release/PremiumDocConverter.apk || echo "APK not found"

    - name: List release directory
      run: ls -la release/

    - name: Store APK file
      uses: actions/upload-artifact@v4
      with:
        name: PremiumDocConverter
        path: app/build/outputs/apk/debug/*.apk
        if-no-files-found: warn
