name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: List generated APK
      run: find app/build/outputs -name "*.apk" | sort

    - name: Display APK information
      run: ls -la app/build/outputs/apk/debug/

    - name: Create release APK for download
      run: |
        mkdir -p release
        cp app/build/outputs/apk/debug/app-debug.apk release/PremiumDocConverter.apk || echo "APK not found"

    - name: Create release zip
      run: |
        cd release
        zip -r PremiumDocConverter.zip .
        cd ..
        ls -la release/

    - name: Generate download URL
      run: |
        echo "Your APK will be available for download at https://github.com/dpandey82/premium-doc-converter/actions/runs/${{ github.run_id }}"
        echo "After the build completes, click on the build and look for the 'Artifacts' section"
